#!/usr/bin/env bash

hc() { herbstclient "$@"; }

feh --bg-fill --no-xinerama $HOME/pictures/wallpapers/wp2.jpg

hc emit_hook reload
hc keyunbind --all
Mod=Mod4
# default_term='urxvtc -depth 32 -bg [85]#2d2d2d'
default_term='alacritty'
# default_term='urxvtc'

hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
# hc keybind $Mod-Alt-j spawn xbacklight -dec 5
# hc keybind $Mod-Alt-k spawn xbacklight -inc 5
hc keybind $Mod-Alt-j spawn ddcutil setvcp 10 - 5
hc keybind $Mod-Alt-k spawn ddcutil setvcp 10 + 5

hc keybind XF86AudioRaiseVolume spawn pamixer -i 3
hc keybind XF86AudioLowerVolume spawn pamixer -d 3
hc keybind XF86AudioMute spawn pamixer -t

hc keybind $Mod+Alt+h spawn $HOME/bin/wmctl.sh suspend
hc keybind $Mod+Alt+l spawn $HOME/bin/wmctl.sh lock

hc keybind $Mod-u spawn rofi -show run
hc keybind $Mod-e spawn rofimoji
hc keybind $Mod-z spawn $HOME/bin/rofi_pdf.sh
hc keybind $Mod-t spawn $HOME/bin/rofi_hcr.sh
hc keybind $Mod-m spawn qutebrowser
hc keybind $Mod-i spawn rofi-pass
hc keybind $Mod-n spawn $HOME/bin/q3terminal.sh
hc keybind $Mod-a spawn $HOME/bin/screenshot.sh
hc keybind $Mod-w spawn $HOME/bin/alacritty-sel.sh

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn ${TERMINAL:-$default_term}

hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

hc keybind $Mod-v split bottom 0.5
hc keybind $Mod-o split right 0.5
hc keybind $Mod-Control-space split explode

resizestep=0.05
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tag_names=( '1 web' '2 com' '3 reading' 4 5 6 7 8 9 f1 f2 f3 f4 f5 f6 f7 f8 f9)
# tag_keys=( {1..9} F1 F2 F3 F4 F5 F6 F7 F8 F9)
tag_names=( '1 web' '2 com' 3 4 5 6 7 8 9 )
tag_keys=( {1..9} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

hc keybind $Mod-dollar spawn $HOME/scripts/tagctl.lua -a
hc keybind $Mod-adiaeresis spawn $HOME/scripts/tagctl.lua -r

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Control-r rotate
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# hc keybind $Mod-space                                                           \
#             or , and . compare tags.focus.curframe_wcount = 2                   \
#                      . cycle_layout +1 vertical horizontal max vertical grid    \
#                , cycle_layout +1
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical max horizontal vertical         \
               , cycle_layout +1

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
# hc keybind $Mod-i jumpto urgent

# hc set verbose 1
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#0E566F'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#0ba4ae'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#ffa500'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

hc unlock
hc detect_monitors

x_offset=0
ms="$(herbstclient list_monitors)"
while IFS= read -r m; do
    num=$(cut -d':' -f1 <<< "$m")
    dimensions=$(cut -d' ' -f2 <<< "$m")
    width=$(cut -d'x' -f1 <<< "$dimensions")
    herbstclient pad "$num" 35
    $HOME/git/ggbar/target/release/ggbar "$x_offset" 0 "$width" 35 "$num" &
    x_offset=$(($xoffset + $width))
done <<< "$ms"

