#!/usr/bin/env bash

# herbstluftwm config

# wallpaper
feh --bg-scale -z $HOME/sync/wallpaper/rotation &

hc() { herbstclient "$@"; }

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4 # super key

# next wallpaper
hc keybind $Mod-w spawn feh --bg-scale -z $HOME/sync/wallpaper/rotation
hc keybind $Mod-udiaeresis spawn killall -s SIGUSR1 redshift

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
#hc keybind $Mod-q close
hc keybind $Mod-Return spawn urxvtc

# basic movement
# focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-b split bottom  0.5
hc keybind $Mod-o split right   0.5
# let the current frame explode into subframes
hc keybind $Mod-odiaeresis split explode # Mod-ö

# resizing frames
resizestep=0.03
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-dollar spawn $HOME/scripts/tagctl.lua -a
hc keybind $Mod-adiaeresis spawn $HOME/scripts/tagctl.lua -r

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-t rotate
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                          \
            or , and . compare tags.focus.curframe_wcount = 2                  \
                     . cycle_layout +1 vertical horizontal max vertical grid   \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab cycle +1
hc keybind $Mod-Shift-Tab cycle -1
hc keybind $Mod-z jumpto urgent

hc keybind $Mod-m spawn qutebrowser --backend webengine --debug
hc keybind $Mod-e spawn urxvtc -e neomutt
hc keybind $Mod-n spawn telegram-desktop
hc keybind $Mod-u spawn rofi -show run
hc keybind $Mod-i spawn rofi-pass
hc keybind $Mod-minus spawn $HOME/scripts/rofi_pdf.sh "$HOME/sync/eth/"
hc keybind $Mod-apostrophe spawn $HOME/scripts/rofi_soundbrett.sh
hc keybind $Mod-a spawn $HOME/scripts/screenshot.sh sel
hc keybind $Mod-Shift-a spawn $HOME/scripts/screenshot.sh selxsel

hc keybind XF86AudioRaiseVolume spawn $HOME/scripts/pulseaudioctl.sh inc 3
hc keybind XF86AudioLowerVolume spawn $HOME/scripts/pulseaudioctl.sh dec 3
hc keybind XF86AudioMute spawn $HOME/scripts/pulseaudioctl.sh toggle
hc keybind XF86MonBrightnessDown spawn light -U 3
hc keybind XF86MonBrightnessUp spawn light -A 3
hc keybind $Mod-Mod1-j spawn light -U 3
hc keybind $Mod-Mod1-k spawn light -A 3
hc keybind $Mod-Mod1-h spawn $HOME/scripts/lock_blur.sh suspend
hc keybind $Mod-Mod1-l spawn $HOME/scripts/lock_blur.sh lock

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# panel
panel=$HOME/.config/herbstluftwm/polybar.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/polybar.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done

# $HOME/scripts/indicator-kdeconnect.sh &
