require("vis")
require("plugins/filetype")
require("plugins/complete-word")
require("vis-commentary")
require("vis-git-status")

vis.events.subscribe(vis.events.INIT, function()
    vis:command("set theme base16-solar-flare")
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
    vis:command("set autoindent on")
    vis:command("set numbers on")
    vis:command("set expandtab on")
    vis:command("set cursorline on")
    vis:command("set tabwidth 4")
    vis:command("set colorcolumn 80")
end)
