#!/usr/bin/env bash

fg_red="$(tput setaf 1)"
fg_green="$(tput setaf 2)"
fg_yellow="$(tput setaf 3)"
fg_blue="$(tput setaf 4)"
reset="$(tput sgr0)"

bat() {
    bat0=$(cat /sys/class/power_supply/BAT0/capacity)
    bat1=$(cat /sys/class/power_supply/BAT1/capacity)
    s0=$(cat /sys/class/power_supply/BAT0/status)
    s1=$(cat /sys/class/power_supply/BAT1/status)
    col0="$fg_green"
    col1="$fg_green"
    if (( "$bat0" < 66 )); then
        col0="$fg_yellow"
    fi
    if (( "$bat0" < 33 )); then
        col0="$fg_red"
    fi
    if (( "$bat1" < 66 )); then
        col1="$fg_yellow"
    fi
    if (( "$bat1" < 33 )); then
        col1="$fg_red"
    fi
    echo "BAT0: $col0$bat0%$reset ($s0) / BAT1: $col1$bat1%$reset ($s1)"
}

date="$(date)"
battery="$(bat)"
uptime="$(uptime -p)"
kernel="$(uname -r)"
temp="$(echo $(acpi -t | cut -d' ' -f4)°)"

echo "$fg_blue""BATTERY: ""$reset$battery"
echo "$fg_blue""TEMP:    ""$reset$temp"
echo "$fg_blue""KERNEL:  ""$reset$kernel"
echo "$fg_blue""UPTIME:  ""$reset$uptime"
echo "$fg_blue""DATE:    ""$reset$date"
